tipoff/addresses

- composer.json
- database/factories/CustomerFactory.php
- database/migrations/2020_05_01_100000_create_customers_table.php.stub
- src/AddressesServiceProvider.php
- src/Models/Customer.php
- Move model
- Move factory
- Move migration
> Moving Customer model, factory, migration.

- composer.json
- src/Models/Customer.php
> [TGER-60] - remove guarded property

- composer.json
- src/Nova/Customer.php
- Bump dependencies to the latest version.
- Migrate Nova resource.
> [TGER-59] Migrate nova resources.

- composer.json
- src/AddressesServiceProvider.php
> [TGER-72] - register nova resources

- database/migrations/2021_02_13_100000_add_customer_permissions.php
closes #25 
- created permissions and assign to admin role via the new BasePermissionsMigration
> use new BasePermissionsMigration

- composer.json
- src/Policies/AddressPolicy.php
Created AddressPolicy closes #40
> Add AddressPolicy

- src/Policies/AddressPolicy.php
- src/Policies/CityPolicy.php
- src/Policies/CountryPolicy.php
- src/Policies/RegionPolicy.php
- src/Policies/StatePolicy.php
- src/Policies/TimezonePolicy.php
- src/Policies/ZipCodePolicy.php
policies for City, State, Country, Region, ZipCode
> Add policies for new models

- README.md
> Models readme

- src/Models/Address.php
- src/Models/Country.php
- src/Models/DomesticAddress.php
- src/Models/Region.php
- src/Models/State.php
- src/Models/Timezone.php
- src/Models/Zip.php
- src/Transformers/AddressTransformer.php
- src/Transformers/CountryTransformer.php
- src/Transformers/DomesticAddressTransformer.php
- src/Transformers/RegionTransformer.php
- src/Transformers/StateTransformer.php
- src/Transformers/TimezoneTransformer.php
- src/Transformers/ZipTransformer.php
- tests/Unit/Transformers/AddressTransformerTest.php
- tests/Unit/Transformers/CountryTransformerTest.php
- tests/Unit/Transformers/DomesticAddressTransformerTest.php
- tests/Unit/Transformers/RegionTransformerTest.php
- tests/Unit/Transformers/StateTransformerTest.php
- tests/Unit/Transformers/TimezoneTransformerTest.php
- tests/Unit/Transformers/ZipTransformerTest.php
Hit this dependency when wiring in cart/order support
> Adds transformers and tests

- composer.json
- database/migrations/2015_01_01_100000_create_countries_table.php
- database/migrations/2015_01_01_106000_create_country_callingcodes_table.php
- database/migrations/2015_01_01_120000_create_states_table.php
- database/migrations/2015_01_01_130000_create_zips_table.php
- database/migrations/2015_01_01_140000_create_city_zip_table.php
- database/migrations/2015_01_01_150000_create_domestic_addresses_table.php
- database/migrations/2015_01_01_160000_create_phone_areas_table.php
- database/migrations/2015_01_01_170000_create_phones_table.php
- database/migrations/2015_01_01_180000_create_addresses_table.php
- src/Models/City.php
- src/Models/Country.php
- src/Models/CountryCallingcode.php
- src/Models/DomesticAddress.php
- src/Models/Phone.php
- src/Models/PhoneArea.php
- src/Models/Region.php
- src/Models/State.php
- src/Models/Timezone.php
- src/Models/Zip.php
- src/Nova/Address.php
- src/Nova/City.php
- src/Nova/Country.php
- src/Nova/DomesticAddress.php
- src/Nova/Region.php
- src/Nova/State.php
- src/Nova/Timezone.php
- src/Nova/Zip.php
#58 
- add Migration / Model for Phone
_Note:_
There is a format called E.164, varchar(15)
https://www.twilio.com/docs/glossary/what-e164
For _Validation_ and _Formatting_, we can use Twilio if we use E.164
https://www.twilio.com/docs/lookup
> Phone #58 [TGER-111]

- composer.json
- database/factories/CountryCallingcodeFactory.php
- database/factories/PhoneAreaFactory.php
- database/factories/PhoneFactory.php
Honestly not too sure about these.. let me know if anything needs changing.
> factories for phone, phonearea, countrycallingcode

- database/datamigrations/2015_01_01_105002_add_world_callingcode.php
code field should not have a space, ie. should be '1234' not '1 234'
> remove space from code field

- resources/views/addresses/get-phone-js.blade.php
- src/Http/Controllers/Controller.php
- src/Http/Controllers/PhoneController.php
- src/routes/web.php
plain-vanilla version of the Intl phone input using intl-tel-input js library
> javascript version of Intl phone input

- database/migrations/2015_01_01_140000_create_zips_table.php
- database/unused-migrations/2015_01_01_140001_add_zips_null_states.php
- src/Models/State.php
> fix issues with zips data migration

- composer.json
- src/Nova/City.php
- src/Nova/Zip.php
> fix lat lng to float type

- src/Models/Timezone.php
Not sure how you guys tolerated the slowness for so long....  Also, there was a major bug causing all php timezones to be mapped to 'HAST'
> Fix Timezone::getNameFromPHP and performance

- resources/views/domestic-address-search-bar-javascript.blade.php
> Update domestic address javascript component #72 #75 [TGER-140]

- composer.json
- src/AddressesServiceProvider.php
- src/Models/Timezone.php
> Add and register TimezoneInterface

- .github/workflows/run-tests.yml
- CHANGELOG.md
- composer.json
- src/Nova/DomesticAddress.php
added emilianotisato/nova-google-autocomplete-field.  Cannot test because of seo required addresses version conflicting...
> add GoogleAutocomplete

- src/Models/CountryCallingcode.php
- src/Models/Timezone.php
- src/Models/Zip.php
- src/Nova/City.php
- src/Nova/Country.php
- src/Nova/CountryCallingcode.php
- src/Nova/Phone.php
- src/Nova/PhoneArea.php
- src/Nova/State.php
- src/Nova/Timezone.php
- src/Nova/Zip.php
> fixes set 1

- src/Http/Controllers/PhoneFieldController.php
> Replace all spaces with empty string when saving phone number.
